melspec_config:
  clamp: 1.0e-05
  fmax: 32000
  fmin: 40
  hop_length: 512
  n_fft: 2048
  n_mels: 128
  sample_rate: 44100
  scale_factor: 4
  win_length: 1024
model_config:
  channels_scaleup_factor: 1.5
  down_sampling_factor: 3
  down_sampling_times: 7
  hidden_dims: 128
vocab:
  SP: 0
  aa: 1
  ae: 2
  ah: 3
  ao: 4
  aw: 5
  ax: 6
  ay: 7
  b: 8
  ch: 9
  cl: 10
  d: 11
  dh: 12
  dr: 13
  dx: 14
  eh: 15
  er: 16
  ey: 17
  f: 18
  g: 19
  hh: 20
  ih: 21
  iy: 22
  j: 23
  jh: 24
  k: 25
  l: 26
  m: 27
  n: 28
  ng: 29
  ow: 30
  oy: 31
  p: 32
  q: 33
  r: 34
  s: 35
  sh: 36
  t: 37
  th: 38
  tr: 39
  ts: 40
  uh: 41
  uw: 42
  ux: 43
  v: 44
  vf: 45
  w: 46
  x: 47
  y: 48
  z: 49
  zh: 50
  0: SP
  1: aa
  2: ae
  3: ah
  4: ao
  5: aw
  6: ax
  7: ay
  8: b
  9: ch
  10: cl
  11: d
  12: dh
  13: dr
  14: dx
  15: eh
  16: er
  17: ey
  18: f
  19: g
  20: hh
  21: ih
  22: iy
  23: j
  24: jh
  25: k
  26: l
  27: m
  28: n
  29: ng
  30: ow
  31: oy
  32: p
  33: q
  34: r
  35: s
  36: sh
  37: t
  38: th
  39: tr
  40: ts
  41: uh
  42: uw
  43: ux
  44: v
  45: vf
  46: w
  47: x
  48: y
  49: z
  50: zh
  AP: 0
  <AP>: 0
  <SP>: 0
  ? ''
  : 0
  pau: 0
  a: 0
  axh: 0
  br: 0
  ctrash: 0
  dz: 0
  e: 0
  ee: 0
  el: 0
  em: 0
  en: 0
  exh: 0
  h: 0
  hx: 0
  i: 0
  kl: 0
  nn: 0
  'no': 0
  o: 0
  oo: 0
  rr: 0
  spn: 0
  trash: 0
  tx: 0
  ug: 0
  ve: 0
  vtrash: 0
  uu: 0
  <vocab_size>: 51
